
package mypackage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WsDemoImplService", targetNamespace = "http://svc.tc.org/", wsdlLocation = "http://localhost:8080/WebserviceDemo?wsdl")
public class WsDemoImplService
    extends Service
{

    private final static URL WSDEMOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSDEMOIMPLSERVICE_EXCEPTION;
    private final static QName WSDEMOIMPLSERVICE_QNAME = new QName("http://svc.tc.org/", "WsDemoImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WebserviceDemo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSDEMOIMPLSERVICE_WSDL_LOCATION = url;
        WSDEMOIMPLSERVICE_EXCEPTION = e;
    }

    public WsDemoImplService() {
        super(__getWsdlLocation(), WSDEMOIMPLSERVICE_QNAME);
    }

    public WsDemoImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSDEMOIMPLSERVICE_QNAME, features);
    }

    public WsDemoImplService(URL wsdlLocation) {
        super(wsdlLocation, WSDEMOIMPLSERVICE_QNAME);
    }

    public WsDemoImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSDEMOIMPLSERVICE_QNAME, features);
    }

    public WsDemoImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsDemoImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsDemoImpl
     */
    @WebEndpoint(name = "WsDemoImplPort")
    public WsDemoImpl getWsDemoImplPort() {
        return super.getPort(new QName("http://svc.tc.org/", "WsDemoImplPort"), WsDemoImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsDemoImpl
     */
    @WebEndpoint(name = "WsDemoImplPort")
    public WsDemoImpl getWsDemoImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://svc.tc.org/", "WsDemoImplPort"), WsDemoImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSDEMOIMPLSERVICE_EXCEPTION!= null) {
            throw WSDEMOIMPLSERVICE_EXCEPTION;
        }
        return WSDEMOIMPLSERVICE_WSDL_LOCATION;
    }

}
